from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal
import django.utils.timezone
import datetime

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Society',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=255)),('registration_number',models.CharField(blank=True,max_length=120)),('registration_date',models.DateField(blank=True,null=True)),('address',models.TextField(blank=True)),('city',models.CharField(default='Mumbai',max_length=100)),('state',models.CharField(default='Maharashtra',max_length=100)),('pincode',models.CharField(blank=True,max_length=10)),('default_bill_day',models.PositiveSmallIntegerField(default=5)),('default_due_day',models.PositiveSmallIntegerField(default=25)),('interest_enabled',models.BooleanField(default=True)),('interest_rate_pa',models.DecimalField(decimal_places=2,default=Decimal('12.00'),max_digits=6)),('interest_grace_days',models.PositiveSmallIntegerField(default=0)),('interest_on_interest',models.BooleanField(default=False)),('allocation_policy',models.CharField(choices=[('member_directed','Member-directed / manual'),('principal_then_interest','Oldest principal then interest'),('oldest_due','Oldest due date across all components')],default='member_directed',max_length=40)),('compliance_effective_date',models.DateField(default=datetime.date(2026,6,30))),('interest_resolution_reference',models.CharField(blank=True,max_length=120)),('interest_resolution_date',models.DateField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Member',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('member_no',models.CharField(blank=True,max_length=50)),('title',models.CharField(blank=True,max_length=20)),('full_name',models.CharField(max_length=255)),('mobile',models.CharField(blank=True,max_length=20)),('email',models.EmailField(blank=True,max_length=254)),('address',models.TextField(blank=True)),('pan',models.CharField(blank=True,max_length=20)),('is_active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='ChargeHead',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=30)),('name',models.CharField(max_length=100)),('charge_type',models.CharField(choices=[('fixed','Fixed'),('variable','Variable')],default='fixed',max_length=20)),('ledger_code',models.CharField(blank=True,max_length=30)),('system_code',models.CharField(blank=True,max_length=30)),('is_active',models.BooleanField(default=True))],options={'ordering':['name']}),
        migrations.CreateModel(name='Wing',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('society',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='wings',to='society.society')),('code',models.CharField(max_length=20)),('name',models.CharField(blank=True,max_length=100)),('floors',models.PositiveSmallIntegerField(default=0))],options={'ordering':['code']}),
        migrations.CreateModel(name='Flat',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('unit_no',models.CharField(max_length=30)),('floor',models.CharField(blank=True,max_length=30)),('area_sqft',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=10)),('unit_type',models.CharField(choices=[('residential','Residential'),('commercial','Commercial')],default='residential',max_length=20)),('occupancy_status',models.CharField(default='self_occupied',max_length=30)),('is_active',models.BooleanField(default=True)),('society',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='flats',to='society.society')),('wing',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='flats',to='society.wing'))],options={'ordering':['wing__code','unit_no']}),
        migrations.CreateModel(name='BillingPeriod',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=60)),('period_start',models.DateField()),('period_end',models.DateField()),('bill_date',models.DateField()),('due_date',models.DateField()),('interest_calculation_date',models.DateField(blank=True,null=True)),('status',models.CharField(choices=[('draft','Draft'),('generated','Generated'),('review','Review Required'),('approved','Approved'),('locked','Locked')],default='draft',max_length=20)),('approved_at',models.DateTimeField(blank=True,null=True)),('locked_at',models.DateTimeField(blank=True,null=True)),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='approved_billing_periods',to=settings.AUTH_USER_MODEL)),('society',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='billing_periods',to='society.society'))],options={'ordering':['-period_start']}),
        migrations.CreateModel(name='Bill',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('bill_no',models.CharField(max_length=30)),('bill_date',models.DateField()),('due_date',models.DateField()),('status',models.CharField(choices=[('draft','Draft'),('issued','Issued'),('cancelled','Cancelled')],default='draft',max_length=20)),('generated_at',models.DateTimeField(auto_now_add=True)),('issued_at',models.DateTimeField(blank=True,null=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='bills',to='society.flat')),('period',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='bills',to='society.billingperiod'))]),
        migrations.CreateModel(name='FlatMember',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('owner','Owner'),('joint','Joint Member'),('nominee','Nominee')],default='owner',max_length=20)),('from_date',models.DateField(default=django.utils.timezone.localdate)),('to_date',models.DateField(blank=True,null=True)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='member_links',to='society.flat')),('member',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='flat_links',to='society.member'))]),
        migrations.CreateModel(name='FlatChargeRule',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('configured_amount',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=14)),('default_quantity',models.DecimalField(decimal_places=2,default=Decimal('1'),max_digits=14)),('default_rate',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=14)),('effective_from',models.DateField(default=django.utils.timezone.localdate)),('effective_to',models.DateField(blank=True,null=True)),('active',models.BooleanField(default=True)),('charge_head',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='flat_rules',to='society.chargehead')),('flat',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='charge_rules',to='society.flat'))]),
        migrations.CreateModel(name='BillLine',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('line_type',models.CharField(choices=[('charge','Charge'),('interest','Interest'),('adjustment','Adjustment')],default='charge',max_length=20)),('component_code',models.CharField(max_length=60)),('service_period_start',models.DateField()),('service_period_end',models.DateField()),('due_date',models.DateField()),('description',models.CharField(blank=True,max_length=255)),('quantity',models.DecimalField(decimal_places=2,default=Decimal('1'),max_digits=14)),('rate',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=14)),('amount',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=14)),('confirmed',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('bill',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='lines',to='society.bill')),('charge_head',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='bill_lines',to='society.chargehead'))]),
        migrations.CreateModel(name='BillOpeningItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('snapshot_amount',models.DecimalField(decimal_places=2,max_digits=14)),('created_at',models.DateTimeField(auto_now_add=True)),('bill',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='opening_items',to='society.bill')),('source_line',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='opening_snapshots',to='society.billline'))]),
        migrations.CreateModel(name='InterestCharge',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('source_period_start',models.DateField()),('source_period_end',models.DateField()),('calculation_date',models.DateField()),('from_date',models.DateField()),('to_date',models.DateField()),('days',models.PositiveIntegerField(default=0)),('rate_pa',models.DecimalField(decimal_places=2,max_digits=6)),('base_amount',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=14)),('formula',models.CharField(blank=True,max_length=255)),('bill_line',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='interest_charge',to='society.billline')),('source_lines',models.ManyToManyField(blank=True,related_name='interest_as_base',to='society.billline'))]),
        migrations.CreateModel(name='Receipt',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('receipt_no',models.CharField(max_length=30,unique=True)),('receipt_date',models.DateField(default=django.utils.timezone.localdate)),('payment_mode',models.CharField(choices=[('cash','Cash'),('cheque','Cheque'),('neft','NEFT'),('rtgs','RTGS'),('upi','UPI'),('other','Other')],max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('cheque_no',models.CharField(blank=True,max_length=50)),('cheque_date',models.DateField(blank=True,null=True)),('bank_name',models.CharField(blank=True,max_length=150)),('transaction_ref',models.CharField(blank=True,max_length=100)),('narration',models.CharField(blank=True,max_length=255)),('allocation_instruction',models.CharField(blank=True,max_length=255)),('status',models.CharField(choices=[('received','Received / Pending realization'),('cleared','Cleared / Realised'),('bounced','Bounced'),('cancelled','Cancelled')],default='received',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='created_receipts',to=settings.AUTH_USER_MODEL)),('flat',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='receipts',to='society.flat')),('member',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='receipts',to='society.member')),('society',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='receipts',to='society.society'))]),
        migrations.CreateModel(name='ReceiptAllocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('mode',models.CharField(choices=[('manual','Manual'),('auto','Auto'),('advance','Advance')],default='manual',max_length=20)),('note',models.CharField(blank=True,max_length=255)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='receipt_allocations_created',to=settings.AUTH_USER_MODEL)),('bill_line',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='receipt_allocations',to='society.billline')),('receipt',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='allocations',to='society.receipt'))]),
        migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=80)),('model_name',models.CharField(max_length=100)),('object_id',models.CharField(blank=True,max_length=100)),('details',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='chargehead',constraint=models.UniqueConstraint(fields=('code',),name='uniq_charge_head_code')),
        migrations.AddConstraint(model_name='wing',constraint=models.UniqueConstraint(fields=('society','code'),name='uniq_wing_code')),
        migrations.AddConstraint(model_name='flat',constraint=models.UniqueConstraint(fields=('society','unit_no'),name='uniq_flat_unit')),
        migrations.AddConstraint(model_name='billingperiod',constraint=models.UniqueConstraint(fields=('society','period_start','period_end'),name='uniq_billing_period')),
        migrations.AddConstraint(model_name='bill',constraint=models.UniqueConstraint(fields=('period','flat'),name='uniq_bill_period_flat')),
        migrations.AddConstraint(model_name='flatmember',constraint=models.UniqueConstraint(fields=('flat','member','role'),name='uniq_flat_member_role')),
        migrations.AddConstraint(model_name='flatchargerule',constraint=models.UniqueConstraint(fields=('flat','charge_head','effective_from'),name='uniq_flat_charge_effective')),
        migrations.AddConstraint(model_name='billline',constraint=models.UniqueConstraint(fields=('bill','component_code'),name='uniq_bill_component_code')),
        migrations.AddConstraint(model_name='billopeningitem',constraint=models.UniqueConstraint(fields=('bill','source_line'),name='uniq_bill_opening_source')),
        migrations.AddConstraint(model_name='receiptallocation',constraint=models.UniqueConstraint(fields=('receipt','bill_line'),name='uniq_receipt_billline_allocation')),
    ]
