# Generated by Django 5.2.6 on 2026-09-18 08:52

import django.db.models.deletion
import django.utils.timezone
import society.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_ledger_rules_and_allocation_reversals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('society_register', 'Society register (wings, flats, members)'), ('charge_rules', 'Flat charge rules (fixed / variable amounts)')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('imported', 'Imported'), ('discarded', 'Discarded')], default='uploaded', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('error', 'Error'), ('duplicate', 'Exists — skipped'), ('imported', 'Imported')], default='valid', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('target', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='InterestSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate_pa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'ordering': ['source_line_id', 'from_date'],
            },
        ),
        migrations.CreateModel(
            name='SocietyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ca', 'CA / Accountant'), ('operator', 'Operator'), ('society_admin', 'Society Admin'), ('auditor', 'Auditor (read-only)')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['bill_no']},
        ),
        migrations.AlterModelOptions(
            name='billline',
            options={'ordering': ['service_period_start', 'line_type', 'component_code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='chargehead',
            options={'ordering': ['knockoff_priority', 'name']},
        ),
        migrations.AlterModelOptions(
            name='flatchargerule',
            options={'ordering': ['flat__unit_no', 'charge_head__knockoff_priority', 'effective_from']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-receipt_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='receiptallocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receiptallocationreversal',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='uniq_bill_period_flat',
        ),
        migrations.RemoveConstraint(
            model_name='chargehead',
            name='uniq_charge_head_code',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='society.society'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bill',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='society.society'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_billing_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='interest_resolution_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_billing_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_billing_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billline',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billline',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_bill_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargehead',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_heads', to='society.society'),
        ),
        migrations.AddField(
            model_name='flatchargerule',
            name='resolution_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='interest_on_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='society.society'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bounced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bounced_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='society',
            name='enforce_maker_checker',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('review', 'Review'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='society.bill'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='line_type',
            field=models.CharField(choices=[('charge', 'Principal'), ('interest', 'Interest'), ('adjustment', 'Adjustment')], default='charge', max_length=20),
        ),
        migrations.AlterField(
            model_name='chargehead',
            name='system_code',
            field=models.CharField(blank=True, help_text='Short prefix used in component references, e.g. MAIN, WATER, INT.', max_length=30),
        ),
        migrations.AlterField(
            model_name='interestcharge',
            name='bill_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interest_charge', to='society.billline'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('received', 'Received / Pending clearance'), ('cleared', 'Cleared / Realised'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTR / transaction reference'),
        ),
        migrations.AlterField(
            model_name='receiptallocation',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual / member-directed'), ('auto', 'Automatic policy'), ('reallocation', 'Reallocation')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='society',
            name='allocation_policy',
            field=models.CharField(choices=[('member_directed', 'Member-directed / manual'), ('principal_then_interest', 'Oldest bill: principal then interest'), ('oldest_due', 'Oldest due component')], default='member_directed', max_length=40),
        ),
        migrations.AlterField(
            model_name='society',
            name='compliance_effective_date',
            field=models.DateField(default=society.models.compliance_effective_default),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['society', '-created_at'], name='society_aud_society_e4320e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='society_aud_model_n_57b21e_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('period', 'flat'), name='uniq_live_bill_period_flat'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('society', 'bill_no'), name='uniq_bill_no_per_society'),
        ),
        migrations.AddConstraint(
            model_name='chargehead',
            constraint=models.UniqueConstraint(fields=('society', 'code'), name='uniq_charge_head_society_code'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('society', 'receipt_no'), name='uniq_receipt_no_per_society'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocationreversal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reversal_amount_positive'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='society.society'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='society.importbatch'),
        ),
        migrations.AddField(
            model_name='interestsegment',
            name='ended_by_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_segments_ended', to='society.receiptallocation'),
        ),
        migrations.AddField(
            model_name='interestsegment',
            name='interest_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='society.interestcharge'),
        ),
        migrations.AddField(
            model_name='interestsegment',
            name='source_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_segments', to='society.billline'),
        ),
        migrations.AddField(
            model_name='societymembership',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='society.society'),
        ),
        migrations.AddField(
            model_name='societymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='societymembership',
            constraint=models.UniqueConstraint(fields=('user', 'society'), name='uniq_society_membership'),
        ),
    ]
