# Generated by Django 5.2.6 on 2026-09-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_backfill_society_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='society.society'),
        ),
        migrations.AlterField(
            model_name='chargehead',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_heads', to='society.society'),
        ),
        migrations.AlterField(
            model_name='member',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='society.society'),
        ),
    ]
